upgrade es

diff --git a/elasticsearch/elasticsearch.yml b/elasticsearch/elasticsearch.yml
--- a/elasticsearch/elasticsearch.yml
+++ b/elasticsearch/elasticsearch.yml
@@ -4,142 +4,272 @@ metadata:
   name: db
 
 ---
+# Source: elasticsearch/templates/service.yaml
 kind: Service
 apiVersion: v1
 metadata:
   namespace: db
-  name: elasticsearch
+  name: es-cluster-master
   labels:
-    app.kubernetes.io/name: elasticsearch
-    app.kubernetes.io/instance: elasticsearch
+    heritage: "Helm"
+    release: "elasticsearch"
+    chart: "elasticsearch"
+    app: "es-cluster-master"
+  annotations:
+    {}
 spec:
+  type: ClusterIP
   selector:
-    app.kubernetes.io/name: elasticsearch
+    release: "elasticsearch"
+    chart: "elasticsearch"
+    app: "es-cluster-master"
   ports:
-    - port: 9200
-      name: rest
-    - port: 9300
-      name: inter-node
-
+  - name: http
+    protocol: TCP
+    port: 9200
+  - name: transport
+    protocol: TCP
+    port: 9300
 ---
+# Source: elasticsearch/templates/service.yaml
+kind: Service
+apiVersion: v1
+metadata:
+  name: es-cluster-master-headless
+  namespace: db
+  labels:
+    heritage: "Helm"
+    release: "elasticsearch"
+    chart: "elasticsearch"
+    app: "es-cluster-master"
+  annotations:
+    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
+spec:
+  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
+  # Create endpoints also if the related pod isn't ready
+  publishNotReadyAddresses: true
+  selector:
+    app: "es-cluster-master"
+  ports:
+  - name: http
+    port: 9200
+  - name: transport
+    port: 9300
+---
+# Source: elasticsearch/templates/statefulset.yaml
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   namespace: db
-  name: es-cluster
+  name: es-cluster-master
+  labels:
+    heritage: "Helm"
+    release: "elasticsearch"
+    chart: "elasticsearch"
+    app: "es-cluster-master"
+  annotations:
+    esMajorVersion: "7"
 spec:
-  podManagementPolicy: Parallel
-  serviceName: elasticsearch
-  replicas: 2
+  serviceName: es-cluster-master-headless
   selector:
     matchLabels:
-      app.kubernetes.io/name: elasticsearch
+      app: "es-cluster-master"
+  replicas: 2
+  podManagementPolicy: Parallel
+  updateStrategy:
+    type: RollingUpdate
+  volumeClaimTemplates:
+  - metadata:
+      name: es-cluster-master
+    spec:
+      accessModes:
+      - ReadWriteOnce
+      resources:
+        requests:
+          storage: 30Gi
+      storageClassName: local-path
   template:
     metadata:
+      name: "es-cluster-master"
       labels:
-        app.kubernetes.io/name: elasticsearch
-        app.kubernetes.io/instance: elasticsearch
+        release: "elasticsearch"
+        chart: "elasticsearch"
+        app: "es-cluster-master"
       annotations:
-        fluentbit.io/parser: json
+        fluentbit.io/parser: "json"
+
     spec:
+      securityContext:
+        fsGroup: 1000
+        runAsUser: 1000
+      automountServiceAccountToken: true
       nodeSelector:
-        kubernetes.io/os: linux
-        repe.re/type: "db"
+        repe.re/type: db
       affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
-              matchLabels:
-                app.kubernetes.io/name: elasticsearch
-            topologyKey: "kubernetes.io/hostname"
-      containers:
-      - name: elasticsearch
-        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
+              matchExpressions:
+              - key: app
+                operator: In
+                values:
+                - "es-cluster-master"
+            topologyKey: kubernetes.io/hostname
+      terminationGracePeriodSeconds: 120
+      volumes:
+      enableServiceLinks: true
+      initContainers:
+      - name: configure-sysctl
+        securityContext:
+          runAsUser: 0
+          privileged: true
+        image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.3"
+        imagePullPolicy: "IfNotPresent"
+        command: ["sysctl", "-w", "vm.max_map_count=262144"]
         resources:
-            limits:
-              cpu: 1000m
-            requests:
-              cpu: 100m
-        ports:
-        - containerPort: 9200
-          name: rest
-          protocol: TCP
-        - containerPort: 9300
-          name: inter-node
-          protocol: TCP
+          limits:
+            cpu: 25m
+            memory: 256Mi
+          requests:
+            cpu: 25m
+            memory: 128Mi
+
+      # Currently some extra blocks accept strings
+      # to continue with backwards compatibility this is being kept
+      # whilst also allowing for yaml to be specified too.
+      - command:
+        - sh
+        - -c
+        - chown -R 1000:1000 /usr/share/elasticsearch/data
+        image: busybox
+        name: fix-permissions
+        securityContext:
+          runAsUser: 0
+          privileged: true
         volumeMounts:
-        - name: data
-          mountPath: /usr/share/elasticsearch/data
+          - name: "es-cluster-master"
+            mountPath: /usr/share/elasticsearch/data
+      - command:
+        - sh
+        - -c
+        - ulimit -n 65536
+        image: busybox
+        name: increase-fd-ulimit
+        securityContext:
+          privileged: true
+      containers:
+      - name: "es-cluster"
+        securityContext:
+          capabilities:
+            drop:
+            - ALL
+          runAsNonRoot: true
+          runAsUser: 1000
+        image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.3"
+        imagePullPolicy: "IfNotPresent"
+        readinessProbe:
+          exec:
+            command:
+              - bash
+              - -c
+              - |
+                set -e
+                # If the node is starting up wait for the cluster to be ready (request params: "wait_for_status=green&timeout=5s" )
+                # Once it has started only check that the node itself is responding
+                START_FILE=/tmp/.es_start_file
+
+                # Disable nss cache to avoid filling dentry cache when calling curl
+                # This is required with Elasticsearch Docker using nss < 3.52
+                export NSS_SDB_USE_CACHE=no
+
+                http () {
+                  local path="${1}"
+                  local args="${2}"
+                  set -- -XGET -s
+
+                  if [ "$args" != "" ]; then
+                    set -- "$@" $args
+                  fi
+
+                  if [ -n "${ELASTIC_PASSWORD}" ]; then
+                    set -- "$@" -u "elastic:${ELASTIC_PASSWORD}"
+                  fi
+
+                  curl --output /dev/null -k "$@" "http://127.0.0.1:9200${path}"
+                }
+
+                if [ -f "${START_FILE}" ]; then
+                  echo 'Elasticsearch is already running, lets check the node is healthy'
+                  HTTP_CODE=$(http "/" "-w %{http_code}")
+                  RC=$?
+                  if [[ ${RC} -ne 0 ]]; then
+                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} http://127.0.0.1:9200/ failed with RC ${RC}"
+                    exit ${RC}
+                  fi
+                  # ready if HTTP code 200, 503 is tolerable if ES version is 6.x
+                  if [[ ${HTTP_CODE} == "200" ]]; then
+                    exit 0
+                  elif [[ ${HTTP_CODE} == "503" && "7" == "6" ]]; then
+                    exit 0
+                  else
+                    echo "curl --output /dev/null -k -XGET -s -w '%{http_code}' \${BASIC_AUTH} http://127.0.0.1:9200/ failed with HTTP code ${HTTP_CODE}"
+                    exit 1
+                  fi
+
+                else
+                  echo 'Waiting for elasticsearch cluster to become ready (request params: "wait_for_status=green&timeout=5s" )'
+                  if http "/_cluster/health?wait_for_status=green&timeout=5s" "--fail" ; then
+                    touch ${START_FILE}
+                    exit 0
+                  else
+                    echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=5s" )'
+                    exit 1
+                  fi
+                fi
+          failureThreshold: 3
+          initialDelaySeconds: 10
+          periodSeconds: 10
+          successThreshold: 3
+          timeoutSeconds: 5
+        ports:
+        - name: http
+          containerPort: 9200
+        - name: transport
+          containerPort: 9300
+        resources:
+          limits:
+            cpu: 1000m
+            memory: 6Gi
+          requests:
+            cpu: 1000m
+            memory: 4Gi
         env:
-          - name: cluster.name
-            value: es-raspis
           - name: node.name
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
-          - name: discovery.seed_hosts
-            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch"
           - name: cluster.initial_master_nodes
-            value: "es-cluster-0,es-cluster-1"
-          - name: discovery.zen.minimum_master_nodes
-            value: "1"
+            value: "es-cluster-master-0,es-cluster-master-1,"
+          - name: discovery.seed_hosts
+            value: "es-cluster-master-headless"
+          - name: cluster.name
+            value: "es-cluster"
+          - name: network.host
+            value: "0.0.0.0"
+          - name: cluster.deprecation_indexing.enabled
+            value: "false"
           - name: ES_JAVA_OPTS
-            value: "-Xms4G -Xmx4G"
-        startupProbe:
-          httpGet:
-            path: /_cluster/health
-            port: 9200
-            scheme: HTTP
-          failureThreshold: 10
-          periodSeconds: 10
-        livenessProbe:
-          httpGet:
-            path: /_cluster/health
-            port: 9200
-            scheme: HTTP
-          initialDelaySeconds: 10
-          periodSeconds: 15
-          timeoutSeconds: 10
-          successThreshold: 1
-          failureThreshold: 10
-        readinessProbe:
-          httpGet:
-            path: /_cluster/health?wait_for_status=green&timeout=120s
-            port: 9200
-            scheme: HTTP
-          initialDelaySeconds: 10
-          periodSeconds: 15
-          timeoutSeconds: 120
-          successThreshold: 1
-          failureThreshold: 10
-      initContainers:
-      - name: fix-permissions
-        image: busybox
-        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
-        securityContext:
-          privileged: true
+            value: "-Xmx2g -Xms2g"
+          - name: node.data
+            value: "true"
+          - name: node.ingest
+            value: "true"
+          - name: node.master
+            value: "true"
+          - name: node.ml
+            value: "false"
+          - name: node.remote_cluster_client
+            value: "false"
         volumeMounts:
-        - name: data
-          mountPath: /usr/share/elasticsearch/data
-      - name: increase-vm-max-map
-        image: busybox
-        command: ["sysctl", "-w", "vm.max_map_count=262144"]
-        securityContext:
-          privileged: true
-      - name: increase-fd-ulimit
-        image: busybox
-        command: ["sh", "-c", "ulimit -n 65536"]
-        securityContext:
-          privileged: true
-  volumeClaimTemplates:
-  - metadata:
-      name: data
-      labels:
-        app.kubernetes.io/name: elasticsearch
-        app.kubernetes.io/instance: elasticsearch
-    spec:
-      accessModes: [ "ReadWriteOnce" ]
-      storageClassName: local-path
-      resources:
-        requests:
-          storage: 10Gi
+          - name: "es-cluster-master"
+            mountPath: /usr/share/elasticsearch/data
